export enum PlateauDatasetType {
  Border = "Border",
  Bridge = "Bridge",
  Building = "Building",
  CityFurniture = "CityFurniture",
  EmergencyRoute = "EmergencyRoute",
  GenericCityObject = "GenericCityObject",
  HighTideRisk = "HighTideRisk",
  InlandFloodingRisk = "InlandFloodingRisk",
  LandSlideRisk = "LandSlideRisk",
  LandUse = "LandUse",
  Landmark = "Landmark",
  Park = "Park",
  Railway = "Railway",
  RiverFloodingRisk = "RiverFloodingRisk",
  Road = "Road",
  Shelter = "Shelter",
  Station = "Station",
  TsunamiRisk = "TsunamiRisk",
  UrbanPlanning = "UrbanPlanning",
  UseCase = "UseCase",
  Vegetation = "Vegetation",
}
