import {
  BORDER_LAYER,
  BRIDGE_LAYER,
  CITY_FURNITURE_LAYER,
  EMERGENCY_ROUTE_LAYER,
  GENERIC_CITY_OBJECT_LAYER,
  HIGH_TIDE_RISK_LAYER,
  INLAND_FLOODING_RISK_LAYER,
  LANDMARK_LAYER,
  LAND_SLIDE_RISK_LAYER,
  LAND_USE_LAYER,
  PARK_LAYER,
  RAILWAY_LAYER,
  RIVER_FLOODING_RISK_LAYER,
  ROAD_LAYER,
  SHELTER_LAYER,
  STATION_LAYER,
  TSUNAMI_RISK_LAYER,
  URBAN_PLANNING_LAYER,
  USE_CASE_LAYER,
  VEGETATION_LAYER,
} from "../../../prototypes/view-layers";

export type GeneralLayerType =
  | typeof BORDER_LAYER
  | typeof BRIDGE_LAYER
  | typeof CITY_FURNITURE_LAYER
  | typeof EMERGENCY_ROUTE_LAYER
  | typeof GENERIC_CITY_OBJECT_LAYER
  | typeof INLAND_FLOODING_RISK_LAYER
  | typeof HIGH_TIDE_RISK_LAYER
  | typeof LAND_USE_LAYER
  | typeof LANDMARK_LAYER
  | typeof LAND_SLIDE_RISK_LAYER
  | typeof PARK_LAYER
  | typeof RAILWAY_LAYER
  | typeof RIVER_FLOODING_RISK_LAYER
  | typeof ROAD_LAYER
  | typeof SHELTER_LAYER
  | typeof STATION_LAYER
  | typeof TSUNAMI_RISK_LAYER
  | typeof URBAN_PLANNING_LAYER
  | typeof USE_CASE_LAYER
  | typeof VEGETATION_LAYER;
